--DROP TABLE "[C_NO]_ATT";
--DROP TABLE ADMIN;
--DROP TABLE CLASS;
--DROP TABLE DEPT;
--DROP TABLE PROF;
--DROP TABLE PROFBOARD;
--DROP TABLE STUDENT;
--DROP TABLE SYSBOARD;
--COMMIT;
CREATE TABLE DEPT (
    D_NO    NUMBER  PRIMARY KEY,
    D_NAME  VARCHAR2(100)   NOT NULL    UNIQUE,
    D_PHONE VARCHAR2(100)		NOT NULL    UNIQUE,
	D_HEAD	VARCHAR2(100)		NOT NULL
);

CREATE TABLE PROF (
	P_NO	NUMBER		PRIMARY KEY,
	P_NAME	VARCHAR2(100)		NOT NULL,
	P_ID	VARCHAR2(100)		NOT NULL    UNIQUE,
	P_PWD	VARCHAR2(100)		NOT NULL,
	P_PHONE	VARCHAR2(100)		NOT NULL    UNIQUE,
	P_ENROLL_DATE	TIMESTAMP	DEFAULT SYSDATE	NOT NULL,
	P_QUIT_YN	CHAR(1)	DEFAULT 'N' CHECK(P_QUIT_YN IN ('Y', 'N')),
	D_NO	NUMBER		NOT NULL,
    CONSTRAINT FKD1_NO FOREIGN KEY (D_NO) 
    REFERENCES DEPT (D_NO)
    ON DELETE CASCADE
);

CREATE TABLE STUDENT (
	STU_NO	NUMBER		PRIMARY KEY,
	STU_NAME	VARCHAR2(100)		NOT NULL,
	STU_ID	VARCHAR2(100)		NOT NULL    UNIQUE,
	STU_PWD	VARCHAR2(100)		NOT NULL,
	STU_QUIT_YN	CHAR(1)	DEFAULT 'N'	NOT NULL CHECK(STU_QUIT_YN IN ('Y', 'N')),
    STU_PHONE	VARCHAR2(20)		NOT NULL UNIQUE,
	STU_ENROLL_DATE	TIMESTAMP	DEFAULT SYSDATE,
	STU_ADDR	VARCHAR2(100)		NULL,
	D_NO	NUMBER		NOT NULL,
    CONSTRAINT FKD2_NO FOREIGN KEY (D_NO) 
    REFERENCES DEPT (D_NO)
    ON DELETE CASCADE
);

CREATE TABLE ADMIN (
	AD_NO	NUMBER		PRIMARY KEY,
	AD_NAME	VARCHAR2(50)		NOT NULL,
	AD_ID	VARCHAR2(50)		UNIQUE  NOT NULL,
	AD_PWD	VARCHAR2(100)		NOT NULL,
	AD_DATE	TIMESTAMP		DEFAULT SYSDATE
);

CREATE TABLE CLASS (
	C_NO	NUMBER		PRIMARY KEY,
	C_NAME	VARCHAR2(30)		NOT NULL,
	C_TIME	TIMESTAMP   NULL,
	C_ROOM	CHAR(1)		NULL,
	P_NO	NUMBER		NOT NULL,
    CONSTRAINT FKP_NO FOREIGN KEY (P_NO) 
    REFERENCES PROF (P_NO)
    ON DELETE CASCADE
);

CREATE TABLE SIGNUP (
	S_NO	NUMBER		PRIMARY KEY,
	S_TIME	TIMESTAMP	DEFAULT SYSDATE,
	S_QUIT_YN	CHAR(1)	DEFAULT 'N'	CHECK(S_QUIT_YN IN ('Y', 'N')),
	C_NO	NUMBER		NOT NULL,
	STU_NO	NUMBER		NOT NULL,
    CONSTRAINT FKC_NO FOREIGN KEY (C_NO) 
    REFERENCES CLASS (C_NO)
    ON DELETE CASCADE,
    CONSTRAINT FKSTU_NO FOREIGN KEY (STU_NO) 
    REFERENCES STUDENT (STU_NO)
    ON DELETE CASCADE
);

CREATE TABLE SYSBOARD (
	SYS_NO	NUMBER		PRIMARY KEY,
	SYS_TITLE	VARCHAR(100)		NOT NULL,
	SYS_DATE	TIMESTAMP	DEFAULT SYSDATE,
	SYS_CONTENT	VARCHAR2(3000)		NOT NULL,
	AD_NO	NUMBER		NOT NULL,
    CONSTRAINT FKAD3_NO FOREIGN KEY (AD_NO) 
    REFERENCES ADMIN (AD_NO)
    ON DELETE CASCADE
);

CREATE TABLE PROFBOARD (
	PRO_NO	NUMBER		PRIMARY KEY,
	PRO_TITLE	VARCHAR(100)		NOT NULL,
	PRO_DATE	TIMESTAMP	DEFAULT SYSDATE,
	PRO_CONTENT	VARCHAR2(3000)		NOT NULL,
	P_NO	NUMBER		NOT NULL,
	D_NO	NUMBER		NOT NULL,
    CONSTRAINT FKP4_NO FOREIGN KEY (P_NO) 
    REFERENCES PROF (P_NO)
    ON DELETE CASCADE,
    CONSTRAINT FKD5_NO FOREIGN KEY (D_NO) 
    REFERENCES DEPT (D_NO)
    ON DELETE CASCADE
);

--CONSTRAINT 외래키명 FOREIGN KEY (적용 컬럼명)
--     REFERENCES 참조테이블명 (참조테이블 내 참조할 컬럼명)
--     ON DELETE CASCADE(선택 사항)